name: EnderScythe
version: '${project.version}'
main: org.padrewin.enderscythe.EnderScythe
api-version: '1.20'
depend: [ WorldGuard ]
commands:
  enderscythe:
    description: Give a player the EnderScythe or reload the plugin.
    permission: enderscythe.give
    permission-message: You do not have permission to use this command.
  getupgradeitem:
    description: Give a player the EnderScythe or reload the plugin.
    permission: enderscythe.give
    permission-message: You do not have permission to use this command.
permissions:
  enderscythe.give:
    description: Allows the player to give the Enderman Hoe.
    children:
    default: op
