name: EnderScythe
version: '${project.version}'
main: org.padrewin.enderscythe.EnderScythe
api-version: '1.20'
depend: [ WorldGuard ]
author: 'padrewin'
commands:
  enderscythe:
    description: Give a player the EnderScythe or reload the plugin.
    permission: enderscythe.admin
  getupgradeitem:
    description: Give a player the EnderScythe or reload the plugin.
    permission: enderscythe.admin