name: EnderScythe
version: '${project.version}'
main: org.padrewin.enderscythe.EnderScythe
api-version: '1.20'
softdepend: [ WorldGuard ]
author: 'padrewin'
commands:
  enderscythe:
    description: Give a player the EnderScythe or reload the plugin.
    permission: enderscythe.admin
    aliases: [es]
  getupgradeitem:
    description: Gives an EnderScythe shard to yourself.
    permission: enderscythe.admin
    aliases: [esgui, getui, esupgrade]
  giveupgradeitem:
    description: Give a player an EnderScythe shard.
    permission: enderscythe.admin
    aliases: [esgive, esgiveshard]